"""Make claim_line_coverage.id database-generated.

Revision ID: 0014_claim_line_coverage_identity
Revises: 0013_policy_rule_parsed
Create Date: 2025-01-17
"""

from __future__ import annotations

from alembic import op


def _id_column_state(bind) -> tuple[str | None, bool]:
    """
    Returns (column_default, is_identity).
    SQLAlchemy 2.0 compatible execution.
    """
    row = bind.exec_driver_sql(
        """
        SELECT
            column_default,
            (is_identity = 'YES') AS is_identity
        FROM information_schema.columns
        WHERE table_name = 'claim_line_coverage'
          AND column_name = 'id'
        """
    ).fetchone()

    if row is None:
        return None, False

    column_default = row[0]
    is_identity = bool(row[1])
    return column_default, is_identity


# revision identifiers, used by Alembic.
revision = "0014_claim_line_cov_id"
# revision = "0014_claim_line_coverage_identity"
down_revision = "0013_policy_rule_parsed"
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    default, is_identity = _id_column_state(bind)

    # Already identity => nothing to do.
    if is_identity:
        return

    # If already sequence-backed (serial/bigserial), that's already DB-generated => nothing to do.
    if default and "nextval(" in default:
        return

    # If there is some other default (e.g., a constant), drop it first.
    if default:
        op.execute("ALTER TABLE claim_line_coverage " "ALTER COLUMN id DROP DEFAULT")

    # Add IDENTITY only when not already identity and not already sequence-backed.
    op.execute(
        "ALTER TABLE claim_line_coverage " "ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY"
    )


def downgrade() -> None:
    # Best-effort rollback: drop identity if it exists
    op.execute("ALTER TABLE claim_line_coverage " "ALTER COLUMN id DROP IDENTITY IF EXISTS")
